let fName = 'Ameera';
let lName = 'J';
let fullName = fName + lName;
console.log(fName.length);
console.log('\n');
console.log(lName.length);
console.log('\\');
console.log(fullName.length);
let ini = fName[0] + '\t' + lName[0];
console.log(ini);
console.log('\r');
console.log(ini);
console.log(ini.indexOf('J'));
console.log(fName.lastIndexOf('e'));
console.log(fName.indexOf('e'));
console.log(fName.substring(2, 4));
